### ISSUE TITLE
closeToast / toastProps warnings in the console

### ISSUE THREAD

**Issue by dkocich** [fkhadra/react-toastify#1022]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

- dev console prints warnings repeatedly

`react-dom.development.js:86 Warning: React does not recognize the `closeToast` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `closetoast` instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

`react-dom.development.js:86 Warning: React does not recognize the `toastProps` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `toastprops` instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

todo

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

chrome beta - Version 120.0.6099.5 (Official Build) beta (arm64)
"react": "18.2.0",

**Comment by viktordarko** [comment]
I have a similar bug with isLoading:

Warning: React does not recognize the `isLoading` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isloading` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

basic usage:
  const doSomething = async (data) => {
    if (!data) {
      return toast.error("Please fill all the fields correctly");
    }
    const toastId = toast.loading("Doing something...");
    try {
      const response = await fetch(
        `${process.env.REACT_APP_BACKEND_URL}/api/do-something`,
        {
          method: "POST",
          headers: {
            Accept: "application/json",
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            data
          }),
        }
      );
      const parsed = await response.json();
      if (response.ok) {
        return toast.update(toastId, {
          render: parsed.message,
          type: "success",
          theme: "dark",
          isLoading: false,
          autoClose: true,
          closeOnClick: true,
        });
      } else {
        throw new Error(parsed.message);
      }
    } catch (error) {
      toast.update(toastId, {
        render: error.message,
        type: "error",
        isLoading: false,
        autoClose: true,
        closeOnClick: true,
      });
    }
  };
  
  It works properly but logs that on the console

**Comment by viktordarko** [comment]
Actually I just tested it as well with the toast.promise format and it also logs that in the console, even if it works properly.

example:
const doSomething = async (data) => {
  if (!data) {
    return toast.error("Please fill all the fields correctly");
  }

  const fetchData = async () => {
    const response = await fetch(
      `${process.env.REACT_APP_BACKEND_URL}/api/do-something`,
      ...
    const parsed = await response.json();
    if (response.ok) {
      return parsed.message;
    } else {
      throw new Error(parsed.message);
    }
  };

  toast.promise(fetchData(), {
        pending: "Doing Something...",
        success: {
          render({ data }) {
            return data.message;
          },
          theme: "dark",
          autoClose: true,
        },
        error: {
          render({ data }) {
            return data.message;
          },
        },
      }
    );
  };

**Comment by cduff** [comment]
@viktordarko FYI I just created issue https://github.com/fkhadra/react-toastify/issues/1035

**Comment by fkhadra** [comment]
@dkocich can you share an example. Are you using a custom close button ? Thank you

**Comment by dkocich** [comment]
i have CRA  "react-scripts": "5.0.1", with react admin https://marmelab.com/react-admin/ and have `App.tsx` root component where I use 

```
    <div className="App">
...
      <ToastContainer
        autoClose={10000}
        closeOnClick={false}
        draggable
        hideProgressBar={false}
        limit={10}
        newestOnTop={false}
        pauseOnFocusLoss
        pauseOnHover
        position="bottom-right"
        rtl={false}
      />
    </div>
```

then i simply call `toast(t("mytranslation"));` in different files to show some feedback on actions / API calls that users make across the app

**Comment by MahdiMhqq** [comment]
As I encountered the same issue I created this sandbox for example. I've used `Typography` for content 
wrapper, every time I create a toast the error appear on console.

[See this example](https://codesandbox.io/p/devbox/vite-react-ts-forked-5vp62c?file=%2Findex.html&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwxd8mxk00063b6ljn9wslr1%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwxd8mxj00023b6l9jahhlwj%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwxd8mxj00043b6l4tdf7od9%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwxd8mxj00053b6ltisi4jeq%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwxd8mxj00023b6l9jahhlwj%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwxd8mxj00013b6lp0b7mfct%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clwxde5fm00023b6muno3nhuc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A21%252C%2522startColumn%2522%253A22%252C%2522endLineNumber%2522%253A21%252C%2522endColumn%2522%253A22%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clwyzm5zi00023b6mc825b8yi%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A11%252C%2522startColumn%2522%253A5%252C%2522endLineNumber%2522%253A11%252C%2522endColumn%2522%253A5%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clx64tq3700023b6mplb3a0cj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A9%252C%2522startColumn%2522%253A12%252C%2522endLineNumber%2522%253A9%252C%2522endColumn%2522%253A12%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fmain.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clwxd8mxj00023b6l9jahhlwj%2522%252C%2522activeTabId%2522%253A%2522clwxd8mxj00013b6lp0b7mfct%2522%257D%252C%2522clwxd8mxj00053b6ltisi4jeq%2522%253A%257B%2522id%2522%253A%2522clwxd8mxj00053b6ltisi4jeq%2522%252C%2522activeTabId%2522%253A%2522clx63mjfa00c23b6mb97m76iy%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A5174%252C%2522id%2522%253A%2522clx63mjfa00c23b6mb97m76iy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clwxd8mxj00043b6l4tdf7od9%2522%253A%257B%2522id%2522%253A%2522clwxd8mxj00043b6l4tdf7od9%2522%252C%2522activeTabId%2522%253A%2522clwxdf36p003k3b6msizjfh7w%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwxdf36p003k3b6msizjfh7w%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clwxdf3hv001cdjeoded380fm%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

![Screenshot 2024-06-08 at 5 47 02 PM](https://github.com/fkhadra/react-toastify/assets/90528664/7db17186-932e-4615-9e7d-5ab51971abc4)

Personally I guess the issue comes from these lines in the package, where the `toastProps` and `closeToast` have passed to cloned content element as Props.

```ts
    // src/core/containerObserver.ts
    // line: 174
    .
    .
    .
    if (isValidElement(content) && !isStr(content.type)) {
      toastContent = cloneElement(content as ReactElement, {
        closeToast,
        toastProps,
        data
      });
    } else if (isFn(content)) {
      toastContent = content({ closeToast, toastProps, data: data as TData });
    }
    .
    .
    .
```

**Comment by fkhadra** [comment]
This issue has been inactive for a while, so I'm closing it. If it's still relevant, feel free to reopen or create a new issue with updated details. Thanks for your understanding!

**Comment by phazei** [comment]
This is still relevant.  We've been having this for a while.
`"react-toastify": "~11.0.5",`

```
Warning: React does not recognize the `closeToast` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `closetoast` instead. If you accidentally passed it from a parent component, remove it from the DOM element. Error Component Stack

Warning: React does not recognize the `toastProps` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `toastprops` instead. If you accidentally passed it from a parent component, remove it from the DOM element. Error Component Stack

Warning: React does not recognize the `isPaused` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `ispaused` instead. If you accidentally passed it from a parent component, remove it from the DOM element. Error Component Stack
```

Usually we see this when something is passing a prop to a component that gets plugged onto a element.  For example:

```
const ComponentWidget: React.FC = observer(({
    stuff,
    ...otherProps
}) => {

    return (
        <div ...otherProps />
    )

```

In cases where we had propDrilling and unexpected props being passed from bad data that didn't really harm anything we solved like so:

```
    const { closeToast, toastProps, isClosed, ...remainingProps } = otherProps
    return (
        <div ...remainingProps />
    )
```
