### ISSUE TITLE
get versioned docs

### ISSUE THREAD

**Issue by Guiw5** [fkhadra/react-toastify#1158]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
I just get the docs for the latest version. 

**What is the expected behavior?**
v8.react-toastify.com
v9.react-toastify.com
react-toastify.com

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
No react/browser/Os versions gets affected.

**Comment by fkhadra** [comment]
Hey @Guiw5, this is something I should have done from the beginning. Being the sole maintainer this is not something I can do unfortunately. Although breaking changes are painful, I encourage people to upgrade whenever possible, the doc does keep a list of breaking change for every version since v8. Thank you for your understanding
