### ISSUE TITLE
Make Notifications Session or User Specific

### ISSUE THREAD

**Issue by merrilj** [fkhadra/react-toastify#136]
Hey there,

I'm using this awesome notification system for a tv monitoring system I'm working on. My app uses Slack OAuth for signing in users. I have functionality where I send a post request and the toast notifies on the response from the server (through socket-io). However, if user 1 has performed an action, they get the toast notification from the response as intended, but the notification also goes to user 2, user 3, user 4... who are also signed in to the app. And if user 2, 3, or 4 isn't signed in when user 1 sends the notification, the second they sign in they get a boatload of previous notifications. Is there something I'm doing wrong or missing? The notification system is global for anyone signed in even though only a single user is causing the notification.

I'm still fairly new to a lot of this, so any input would be much appreciated!

**Comment by fkhadra** [comment]
Hello @merrilj,

I'm glad you like it.

The notification system(react-toastify) run on the client side and it's stateless. I think your current behavior is due to the way you handle the socket.

If you want to make the notifications specific to each user, you need to specify the socket id when you dispatch the event from the server side.

There are several ways to dispatch events with socket.io regarding your needs:
- dispatch to all user listening to the foo event: `socket.emit('foo', payload)`
- dispatch to all user except the sender(the initiator): `socket.broadcast.emit(event, payload)`
- dispatch to a specific user: socket.to(socketId).emit(event, payload)

I think the last one is the one you are looking for. I hope I understand correctly your issue.

Let me know if I can help.

Cheers

**Comment by merrilj** [comment]
Hi @fkhadra,

Thanks for the input, that's exactly what I'm trying to do. I'll look into it!

**Comment by merrilj** [comment]
Hi again @fkhadra,

So I figured out the user specific issue (thanks for the help), but I have another question:
The toast component only displays on browser focus. If I'm not actively visiting the page when the socket comes through, the dev tools show logs, etc., but the toast doesn't show until I visit the page again where it dumps a ton of previous notifications at once.

Is there an option for making the notifications run while the window is inactive so they don't build up or what would be the best way to work around that?

**Comment by fkhadra** [comment]
Hello @merrilj,

The notification only shows up when the document is active. I'll add a way to opt-out for the next release.

**Comment by merrilj** [comment]
Sounds great, thanks!
