### ISSUE TITLE
custom closeButton element does not close toast

### ISSUE THREAD

**Issue by johlrich** [fkhadra/react-toastify#138]
If you disable `closeOnClick` and supply a custom element to `closeButton`, then you can see that the button will not actually close the toast. When inspecting the virtual dom it appears the `closeToast` function is being placed on a `closeToast` prop instead of `onClick` on the custom element.

You also get the following warning in the console:
> Warning: React does not recognize the `closeToast` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `closetoast` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

Here's a minimal repro showing the issue:
[![Edit lr57w7k5v7](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lr57w7k5v7)

If I'm correct that this is an issue, I can submit a PR with the fix + updated test if you wanted. 

Thanks for the great library!

**Comment by fkhadra** [comment]
Hello @johlrich,

Thanks for the feedback, appreciate.

I modified your sample to make it works. You have to pass a component instead of a node.
Inside your component, you need to bind `closeToast` to the event of your choice to close the toast.

The prop is not called `onClick` but `closeToast` for consistency, one can decide to close the toast by filling an input for instance.

[![Edit x9pqp6j37w](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/x9pqp6j37w)

**Comment by johlrich** [comment]
Makes sense! Thanks again for the feedback and library.

**Comment by JustAPC** [comment]
can we get the answer sandbox back up again? it can't be found

> Hello @johlrich,
> 
> Thanks for the feedback, appreciate.
> 
> I modified your sample to make it works. You have to pass a component instead of a node. Inside your component, you need to bind `closeToast` to the event of your choice to close the toast.
> 
> The prop is not called `onClick` but `closeToast` for consistency, one can decide to close the toast by filling an input for instance.
> 
> [![Edit x9pqp6j37w](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/x9pqp6j37w)
