### ISSUE TITLE
An option to disable all unnecessary styles

### ISSUE THREAD

**Issue by SilencerWeb** [fkhadra/react-toastify#203]
It would be great if u add an option to disable all these unnecessary styles because they override default styles and it is so stupid to override them using cascade, it is much easier just to disable them using one option that can be called like `disableUnnecessaryStyles`

![image](https://user-images.githubusercontent.com/20713191/42753377-2cea91b6-890a-11e8-8c1f-a2e66a43083a.png)
![image](https://user-images.githubusercontent.com/20713191/42753397-3cd050de-890a-11e8-9bcf-2ca3683959d5.png)

**Comment by RickeyWard** [comment]
You have the option to specify the ClassName you want to use. if you don't use the default "Toastify_toast" then these styles won't used.

The CSS is an example of how to use the library, not a requirement.

Included is a non minimized css file, that you can copy to your local project, change to match you site, and then include it in your project instead of the supplies one.

**Comment by fkhadra** [comment]
Hello @SilencerWeb,

I understand your need. Like @RickeyWard said using the css file is not a requirement, you can create your own if you want to.

I'm not considering to add an option to do that for the moment. 

Thank you for your feedback.
