### ISSUE TITLE
Warning when calling toast functions

### ISSUE THREAD

**Issue by heamaral** [fkhadra/react-toastify#213]
When I call toast.error("test") i got the following warning on console:
```
Warning: Unsafe legacy lifecycles will not be called for components using new component APIs.

TransitionGroup uses getDerivedStateFromProps() but also contains the following legacy lifecycles:
  componentWillMount
  componentWillReceiveProps

The above lifecycles should be removed. Learn more about this warning here:
https://fb.me/react-async-component-lifecycle-hooks
```

**Comment by fkhadra** [comment]
Hello @heamaral,

Since React 16.3 `componentWillMount` and `componentWillReceiveProps` are 'deprecated' in favor of `getDerivedStateFromProps` and `getSnapshotBeforeUpdate`.

I need to update react-transition-group from 2.2 to 2.4. Those warning only appear during development, so don't worry for the moment. 

The next release is scheduled for this month.

More detail about react lifecycle [here](https://reactjs.org/docs/react-component.html)

**Comment by marinbgd** [comment]
This is still an issue.

**Comment by fkhadra** [comment]
Hey @marinbgd,

Did you upgrade to the latest version ?

**Comment by marinbgd** [comment]
Yes.
The version of react-toastify is 4.4.0.
react@16.4.2

**Comment by fkhadra** [comment]
Are you using `react-transition-group` somewhere else ?

Maybe you can try to remove your lock file and reinstall the packages to be sure that the correct version of the dependencies are installed.

**Comment by marinbgd** [comment]
I do not have _react-transition-group_ in package.json...
I will try your suggestion, maybe its just "that" :)

**Comment by Petar-np** [comment]
react-transition-group package is where this error comes from
