### ISSUE TITLE
autoClose is based on the progress bar animation

### ISSUE THREAD

**Issue by lorenzos** [fkhadra/react-toastify#27]
If I write a custom CSS without progress bar animation (let's say I do not want to use them, so they are always hidden and I don't care styling them), the toast never closes itself, despite the `autoClose` property.

I think this is conceptually wrong, I mean, relying on something visual and completely optional to implement an apparently non-related key feature. Also, this break compatibility with IE9 because it does not support CSS animations events (assuming we care about IE11-).

I can work on a PR to make `autoClose` work just with normal `setInterval` if you prefer.

**Comment by fkhadra** [comment]
Actually, before I implement the progress bar  I was managing the timer myself. You can have a look at the first release.

When I decided to introduce the progress bar, I thought also that relying on animation is conceptually wrong but I decided to choose simplicity. I mean the dom api is there for a reason.

You can still use the autoClose without the progress bar by simply hiding it:

```js
<ToastContainer hideProgressBar={false} />
```
What we could think about is a fallback to `setInterval` when animations are not supported.

To manage animation event I rely on  `animation-play-state` which is implemented on all evergreen browser and it's also supported by IE >= 10. I also need to tell postcss to include ie prefix.

But in the meantime, I understand your point of view. The component must implement a fallback to setInterval and/or let the user choose the strategy.

**Comment by fkhadra** [comment]
Hey @lorenzos ,

Since all browser support animation-play-state I don't think I'm gonna change something.

**Comment by StJohn3D** [comment]
So this just bit me, I defined my own css transitions, and styles, so I didn't think I needed to import the [ReactToastify.css](https://github.com/fkhadra/react-toastify/blob/master/dist/ReactToastify.css)

After spending a couple hours racking my brain for why everything else worked except for autoclose, I thankfully came across this issue. It still took another half hour before it clicked, that the reason it wasn't working was because I didn't have the css transitions for the _progress bar_ imported.

So if anyone else is seeing `animation-play-state: running;` and wondering why the animation never finishes, that's why - it needs the `@keyframes Toastify__trackProgress` imported somewhere so toast can find it.

**Comment by ondratra** [comment]
I had the same issue caused by different reason. I was using `preact` version `10.0.0-rc.0` that had [bug](https://github.com/preactjs/preact/pull/1804) around transition handling and that caused toast not to `autoClose` (close via button worked fine). One of symptoms was seeing `animation-play-state: running;` on toast element like @StJohn3D mentioned. With release of `preact` version [10.0.0-rc.1](https://github.com/preactjs/preact/releases/tag/10.0.0-rc.1) issue is gone.

I guess a similar [issue](https://github.com/fkhadra/react-toastify/issues/32#issuecomment-448116163) with `autoClose` was also resolved by updating 3rd party package (react / preact / etc.).

**Comment by vikrant-gembrill** [comment]
on mouse click anywhere on the page, the animation pauses and resumes on hover, how can we disable this feature so that the animation continues no matter what?

**Comment by fkhadra** [comment]
@vikrant-gembrill you can set `pauseOnHover` to `false` 

```js
toast("hello", { pauseOnHover: false })

// Or for all toasts
<ToastContainer pauseOnHover={false} />
```

**Comment by vikrant-gembrill** [comment]
@fkhadra it only works for hover, however, when i **click** anywhere on the page, even outside toast message, the toast animation pauses.
it only resumes when i hover on it.

**Comment by fkhadra** [comment]
@vikrant-gembrill if the toast pause when you click outside of the page you have to set `pauseOnFocusLoss` to `false`
```js
<ToastContainer pauseOnHover={false}  pauseOnFocusLoss={false} />
```

**Comment by vikrant-gembrill** [comment]
@fkhadra yes that has resolved the issue, thanks.
