### ISSUE TITLE
remove soon-to-be-deprecated react lifecycle functions

### ISSUE THREAD

**Issue by iambumblehead** [fkhadra/react-toastify#323]
**Do you want to request a *feature* or report a *bug*?**

Both. When using inferno with the latest version of redux and toastify, this warning is shown in the console,
```
Warning: Unsafe legacy lifecycles will not be called for components using new component APIs.
      TransitionGroup contains the following legacy lifecycles:
      componentWillMount
componentWillReceiveProps
      The above lifecycles should be removed.
```

[Those functions will be deprecated in future version of react,][0] and inferno renders a big red warning message when it discovers them in react-toastify.

[0]: https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

**Comment by alanlima** [comment]
Hi @iambumblehead 

react-toastify doesn't use those API's so the problem is not here.

Checking the library [react-transition-group](https://github.com/reactjs/react-transition-group), it stopped to use `componentWillMount` and `componentWillReceiveProps` on [v2.4.0](https://github.com/reactjs/react-transition-group/releases/tag/v2.4.0) which is the minimal dependency for `react-toastify`:

https://github.com/fkhadra/react-toastify/blob/8fc64cbe3ba4c16cda137a61358e2e111bc2658f/package.json#L50-L54

The problem might be with Inferno's render.

---
_It is quite extra info for this issue but:_

Checking the source code for `react-transition-group` on `node_modules` the library is compiled to a version that is using componentWillMount (probably for compatibility) and some flags are set to suppress warnings (which react render interprets that but Inferno doesn't)

```javascript
  // React may warn about cWM/cWRP/cWU methods being deprecated.
  // Add a flag to suppress these warnings for this special case.
  componentWillMount.__suppressDeprecationWarning = true;
  componentWillReceiveProps.__suppressDeprecationWarning = true;
  componentWillUpdate.__suppressDeprecationWarning = true;
```

You can check this on `node_modules/react-transition-group/dist/react-transition-group.js`

**Comment by iambumblehead** [comment]
@alanlima thank you so much for spending the time to make this nice response :)

**Comment by alanlima** [comment]
@iambumblehead No worries, happy to help 🤗

**Comment by fkhadra** [comment]
@alanlima thanks for answering !
