### ISSUE TITLE
Strict Mode Supported

### ISSUE THREAD

**Issue by IceSentry** [fkhadra/react-toastify#388]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

When enabling [Strict Mode](https://reactjs.org/docs/strict-mode.html) the console receives a few errors related to using findDOMNode()

**What is the expected behavior?**

No error in the console when using Strict Mode

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React: 16.9
Browser: N/A

Are there any plans to migrate to newer React API's to make Strict Mode work?

**Comment by fkhadra** [comment]
Hello @IceSentry,

The library don't use `findDOMNode` directly. This is used by react-transition-group. I'll see if they have any plan to migrate from it.

Thank you

**Comment by crobinson42** [comment]
When this issue is closed in `react-transition-group` we can update the dependency version in this lib: https://github.com/reactjs/react-transition-group/pull/559

**Comment by fkhadra** [comment]
@crobinson42 thank you for linking the issue appreciate

**Comment by WPaczula** [comment]
There is an updated version of that issue on the `react-transition-group`: https://github.com/reactjs/react-transition-group/issues/606

**Comment by fkhadra** [comment]
Thanks @WPaczula

**Comment by darklight9811** [comment]
Is there a workaround? The toasts won't even display for me.

**Comment by ifier** [comment]
Still happens :(

**Comment by fkhadra** [comment]
The guys of react-transition-group are working really hard to address this issue([PR here](https://github.com/reactjs/react-transition-group/pull/559)). This should land soon.

- Strict mode run in development mode only, this should not impact your production code. 
- The toast should display even with strict mode @darklight9811 
- You should only see a warning with strict mode until the issue is fixed.

Below an example of react-toastify working in strict mode.

[![Edit relaxed-water-ov9it](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/relaxed-water-ov9it?fontsize=14&hidenavigation=1&theme=dark)

**Comment by fkhadra** [comment]
The new RC of `react-toastify` support strict mode 🔥. You can install it as follow:
`yarn add react-toastify@next` or `npm i react-toastify@next`

I expect to launch the stable release next week if there is no bug.

**Comment by fkhadra** [comment]
There is a really weird bug when a single notification is displayed the exit transition is not triggered. I'll investigate that bug later

**Comment by fkhadra** [comment]
Everything has been fixed for strict mode.
