### ISSUE TITLE
Issue with overwriting styles from Material UI Theme

### ISSUE THREAD

**Issue by railto** [fkhadra/react-toastify#427]
Hi folks, thanks for creating and maintaining this project, just got a (hopefully small) bug that I'm running into.

I'm using MaterialUI and have created a custom theme where I'm setting different font sizes for H1 etc. Throughout the app this works fine, except for when I'm rendering a react-toastify message. When I do that, the font size for H1 seems to be reset to browser setting, but when the toast clears from screen it goes back to normal according to my theme.

I've tested this across multiple browsers and same time. The app is using latest versions of React/MaterialUI/react-toastify.

I've also tried using a different toast component and did not have this issue, so it appears to be something specific to react-toastify.

I've included 2 screenshots, one without toast being active and the other with it active.

![without-toast](https://user-images.githubusercontent.com/6123557/75439153-397df300-5951-11ea-87b5-5bd670493ac9.png)
![with-toast](https://user-images.githubusercontent.com/6123557/75439156-3aaf2000-5951-11ea-9df0-108ae0a850cd.png)

Thanks in advance.

Mark

**Comment by railto** [comment]
Just created a codesandbox that shows this issue - https://codesandbox.io/s/react-toastify-material-lpuqn 

Thanks again

**Comment by ibraude** [comment]
Hey, I've been facing the same issue. 

To solve this you should use the <ToastContainer /> component to initialize your toasts, instead of the new toast.configure() method. 
Also, you must place the <ToastContainer /> component within your material-ui <StyleProvider> Component. 

@fkhadra It is unclear to me why the toast component causes an additional insertion of a MuiTypography style sheet, but I'll be happy to add a note regarding this issue to the docs if you'd like. 

Hope this helps

**Comment by railto** [comment]
@ibraude Thanks, only just seen your comment now, got it sorted in a similar fashion
