### ISSUE TITLE
Warning: componentWillReceiveProps has been renamed

### ISSUE THREAD

**Issue by Tsyklop** [fkhadra/react-toastify#428]
Hi. I started my application with `react-toastify 5.5.0` dependency and took warning in google chrome console:

> Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.
> 
> * Move data fetching code or side effects to componentDidUpdate.
> * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
> * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
> 
> Please update the following components: ToastContainer

I use ReactJS 16.12.0 and react-scripts 3.4.0

**Comment by fkhadra** [comment]
Hey @Tsyklop ,

Sorry for the late reply but this issue is not related to react-toastify. componentWillReceiveProps is not used at all. The only warning you could get is about Strict Mode.

The new RC of `react-toastify` support strict mode. You can install it as follow:
`yarn add react-toastify@next` or `npm i react-toastify@next`

I expect to launch the stable release next week if there is no bug.

**Comment by Ahmed-Habbachi** [comment]
Hello. i am facing the exact same warning, and tried to use the @next version but still have the same warning.

**Comment by Tsyklop** [comment]
Problem is still exists.
