### ISSUE TITLE
Animations not working, autoClose not working

### ISSUE THREAD

**Issue by emadow** [fkhadra/react-toastify#47]
Oddly, animations are not working for me at all. When the toast appears, there is no animation. Similarly, when I manually close the toast, there is an abrupt close with no animation. And because `autoClose` is dependent on the animation, **the toast will never close until triggered manually**.

I have the CSS file referenced correctly, and styling seems to work otherwise. My implementation is as follows:

Container:
```jsx
<ToastContainer
    position="top-right"
    type="error"
    autoClose={4000}
    hideProgressBar={false}
    closeOnClick={true}
    pauseOnHover={true}
/>
```
Trigger code (tried placing this in various areas in my code with the same result): 

```jsx
toast('message', {
    type: toast.TYPE.ERROR,
    autoClose: 3000,
    hideProgressBar: false,
    pauseOnHover: true,
});
```

![this](https://user-images.githubusercontent.com/490190/30719333-f20aaabc-9ed7-11e7-9b2c-6957bc606d3f.gif)

I've tried every variation of settings to no avail. This was attempted using the newest versions of Chrome and Safari. What could be going wrong here?

**Comment by fkhadra** [comment]
@emadow I don't have the issue at all.  I'm also using chrome and safari latest version. Do you see any things when you open the developer tools ?

**Comment by emadow** [comment]
@fkhadra no errors in the console. Very puzzling.

**Comment by emadow** [comment]
Ack. Seems to be the result of how webpack was dealing with my imports -- my `@keyframes` were not global.

**Comment by fkhadra** [comment]
Ow I'm glad you fixed it.

**Comment by ilovebeatles** [comment]
@emadow Can you please share your fix? I've stuck with this too.

**Comment by MaxiSantos** [comment]
I'm also having this issue

**Comment by JustFly1984** [comment]
I have CSS modules, and just copied all CSS from the module and added :global prefix to each one. I do not have animations nor autoClose working.

**Comment by fernandolobao** [comment]
I have the same problem as @JustFly1984 , autoclose and animation are not working because I had to put the css rules under :global approach. Does someones have a fiz already?

**Comment by k4st0r42** [comment]
Same problem for me, +1

**Comment by fkhadra** [comment]
Hello,

It would be nice to reproduce the bug via codesandbox. Anyone know how to do this ?

**Comment by k4st0r42** [comment]
I could, but it is possible to update webpack configuration with codesandbox ?

**Comment by k4st0r42** [comment]
Here the code : https://codesandbox.io/s/z252xzmvrl

It does not work on codesandbox because the webpack.config.js is not used (so the modules are not activated by default for css-loader). I don't know if it is possible to configure webpack on codesandbox...

In my project on my PC, the CSS of the toast box works well, but not the autoclose or animations.
If I remove modules and import globally like in your documentation, autoclose and animations work.

**Comment by JustFly1984** [comment]
In my case I use CSS modules, so I can’t just import styles from
node_modules. I’ve copied css, and added global prefix to each class name

**Comment by vijilvpillai** [comment]
Me too facing the same issue. Does anyone know how to fix this webpack issue . The progressbar and auto close is not working

**Comment by chiragbhansali** [comment]
I was using Next.js with CSS Modules and faced a similar issue. I solved it by tweaking the CSS file as follows:

Initial:

```
@keyframes Toastify__slideInUp {
  from {
    transform: translate3d(0, 110%, 0);
    visibility: visible;
  }

  to {
    transform: translate3d(0, 0, 0);
  }
}
```

Final (wrapping the animation name with `:global()`):

```
@keyframes :global(Toastify__slideInUp) {
  from {
    transform: translate3d(0, 110%, 0);
    visibility: visible;
  }

  to {
    transform: translate3d(0, 0, 0);
  }
}
```

Source: [css-modules#115](https://github.com/css-modules/css-modules/issues/115#issuecomment-228224639)

I had to manually add `:global` to all the keyframes, apart from a common `:global` for the other classes. I have made the edited stylesheet with all the `:global`'s added in this [gist](https://gist.github.com/chiragbhansali/466f5906e4be0016f28b4b498cd0a366) so that you don't have to go through the same pain 😅

**Comment by chiragbhansali** [comment]
@fkhadra Can you please add this to the documentation? It might be helpful for people using CSS Modules.

**Comment by vikrant-gembrill** [comment]
on mouse click anywhere on the page, the animation pauses and resumes on hover, how can we disable this feature so that the animation continues and the toast closes ?
