### ISSUE TITLE
Notifications are never removed from dom

### ISSUE THREAD

**Issue by Kepro** [fkhadra/react-toastify#50]
After every item is disappear then we will see in dom react-empty comment, all dead notifications should be removed also internally

**Comment by fkhadra** [comment]
The dead notifications are removed. What you are seeing is the toast's containers which are removed after the n+1 iteration. This is done by design.

When you display a notification we check if for the given position a container exists. If yes, use it otherwise create one. In the meantime, we remove all unused container.

Go to the demo page, open your devtools and wait the end of the notification. You will see 6 containers, 1 for each position:
<img width="550" alt="screen shot 2017-10-01 at 20 55 58" src="https://user-images.githubusercontent.com/5574267/31057918-10c7b2f4-a6eb-11e7-8b4c-5ae3b1549859.png">

Then click on notify to display only one notification. All the containers will be removed except the one used to position the notification:
<img width="497" alt="screen shot 2017-10-01 at 20 58 47" src="https://user-images.githubusercontent.com/5574267/31057951-d1b8efaa-a6eb-11e7-8259-3d4f367e50d1.png">

**Comment by Kepro** [comment]
I'm talking about
![toast1](https://user-images.githubusercontent.com/1714370/31057980-352a4f20-a6ec-11e7-9059-d353d41a1ae7.png)
![toast2](https://user-images.githubusercontent.com/1714370/31057981-352bbd38-a6ec-11e7-83dc-b8824a1169b2.png)

**Comment by fkhadra** [comment]
Can you provide a snippet to reproduce it? 
Mine is getting empty:
<img width="497" alt="screen shot 2017-10-01 at 21 22 50" src="https://user-images.githubusercontent.com/5574267/31058127-cecd3fc8-a6ee-11e7-8dbe-a3e405a304c6.png">

**Comment by Kepro** [comment]
@fkhadra I'm using react 15.6.1 are you testing it on 16.0.0?

**Comment by fkhadra** [comment]
@Kepro  yes I switched to react 16  and the same for the test. You think that it can cause the issue ?

**Comment by Kepro** [comment]
React 16 is handling this in a different way... in react 15.x if you return null then you will see react-empty as I showed in screenshot, but my point was that you still have all elements in your object, so after dismiss you don't remove it from there, this is also wasting memory in application, think if you have some system and it's running 24/7 without reloading and you never remove hidden notifications :)

I don't look at your code, maybe you have internal limit of max notifications and you clearing that queue

**Comment by fkhadra** [comment]
@Kepro  you're right. I clean the "object" when the container is unmounted.  
I got your point, I'll fix this. I guess it will be cleaner. Thanks !

**Comment by Kepro** [comment]
Thanks, sorry for no PR :) but don't have time now...

**Comment by fkhadra** [comment]
Don't worry :D. Finding a bug is a way to contribute

**Comment by dhirendrarathod2000** [comment]
@fkhadra i checked your demo
it removes from everything HTML dom but it keep container on React Dom
