### ISSUE TITLE
Styles not applying immediately to toasts rendered after first one if limit=1

### ISSUE THREAD

**Issue by danyakalnov** [fkhadra/react-toastify#506]
**Do you want to request a *feature* or report a *bug*?**

I want to request a bug

**What is the current behavior?**

Current code: 

<ToastContainer
          limit={1}
          hideProgressBar
          style={{
            display: 'flex',
            justifyContent: 'center',
            marginLeft: '0',
            transform: 'translate(-50%)',
            width: 'auto',
          }}
        />

Then I dispatch toast function from two different places. Second toast is rendered not correctly, but in a moment styles eventually applied.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React: 16.9.0, react-toastify: 6.0.8

Below is the link to the video of observed behavior.
https://drive.google.com/file/d/1hSE8omWZUuqJED01Ohje7rLiBTS19b_W/view?usp=sharing

**Comment by ScotchAndSoda** [comment]
This happens not because the style does not apply immideately, but because new toasts are polled from the queue before a previous toast has finished its exit animation.

[https://github.com/fkhadra/react-toastify/blob/cb7afbe5976f032b6f23c9c838453c5acc88d9b0/src/hooks/useToastContainer.ts#L134](url)

Considering that default animations take 750ms to exit, and there's a fixed 500ms timeout before a queue poll this causes a jerking motion.

@fkhadra, perhaps, the universal solution would be to store toasts' exit duration alongside transition, and use it in setTimeout?

**Comment by fkhadra** [comment]
@ScotchAndSoda good catch. This make senses. I'll try to free some time to work on the fix.

**Comment by fkhadra** [comment]
So after analysis, I don't think that the issue is related to what @ScotchAndSoda mentioned.
This piece of code is called only when the exit animation is **done**. I think the issue is caused by something else. I would need a reproduction to investigate more.

```js
setTimeout(() => { 
   appendToast(toastContent, toastProps, staleId); 
 }, 500);
```
