### ISSUE TITLE
Warning: React does not recognize the `nodeRef` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `noderef` instead

### ISSUE THREAD

**Issue by sashahavia** [fkhadra/react-toastify#511]
I just updated `react-toastify` to `6.0.8` version and getting this error now 

```
Warning: React does not recognize the `nodeRef` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `noderef` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by Toast)
    in Transition (created by ToastTransition)
    in ToastTransition (created by Toast)
    in Toast (created by ToastContainer)
    in div (created by ToastPositioner)
    in ToastPositioner (created by ToastContainer)
    in div (created by ToastContainer)
    in ToastContainer (created by Routes)
    in ErrorBoundary (created by Routes)
    in Routes (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in withRouter(Connect(Routes))
    in Router (created by BrowserRouter)
    in BrowserRouter
    in Provider
```

**Comment by fkhadra** [comment]
Hey,

Could you provide a codesanbox reproduction thanks.

**Comment by gnoesiboe** [comment]
I suspect this [`{...props}`](https://github.com/fkhadra/react-toastify/blob/44ed0334bd25f1b0352ed08053f523179864bd9d/src/types/index.ts) might be the problem. As `nodeRef` is part of `ToastTransitionProps`, it is passed to the `<Transition />` component. Maybe something changed in `react-transition-group` recently? When I look into their code I see the props [being added to a `div`-element](https://github.com/reactjs/react-transition-group/blob/master/src/TransitionGroup.js#L107) that will probably result in this warning.

This could be fixed by making sure that `nodeRef` is pulled from the rest props (`{...props}`)?

**Comment by fkhadra** [comment]
Hey @gnoesiboe, are you able to reproduce the issue ?

Thanks

**Comment by gnoesiboe** [comment]
@fkhadra I ran into this issue myself. That is how I ended up here.

**Comment by fkhadra** [comment]
@gnoesiboe if you have time could you try to reproduce the issue on codesandbox or share the repo if it's public. Thanks!

**Comment by gnoesiboe** [comment]
Sharing is not possible I'm afraid. And time is something I do not have at this point. I'll put it on my todo list but it won't be somewhere on top..

**Comment by fkhadra** [comment]
No problem. Thank you anyway.

**Comment by fkhadra** [comment]
This will be fixed with the new release. I'm removing the dependency to `react-transition-group`

**Comment by gnoesiboe** [comment]
ah, nice! Thanks!
