### ISSUE TITLE
Flex layout issue in IE11 (includes fix suggestion)

### ISSUE THREAD

**Issue by jkamleh** [fkhadra/react-toastify#572]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Using flex layout (Bootstrap 4) inside `Toastify__toast-body` class has issues rendering in IE11, works fine in latest Chrome. Example is with one fixed column width (col-md-3) and second column dynamic (col):
![image](https://user-images.githubusercontent.com/14323780/108926899-382ff500-768f-11eb-9f62-8ee346d9531f.png)

**Proposed fix:**
As other users may encounter this while trying to support IE11, suggest adding `width: 100%;`  style by default in https://github.com/fkhadra/react-toastify/blob/7ec50404e883ea88e9cab2019857ef96fb072776/scss/_toast.scss#L39-L42

I'm temporarily fixing this by applying the following in my CSS, please advise if this above recommendation is suitable, if so I can create a PR (or feel free to apply):
```CSS
.Toastify__toast-body {
    width: 100%;
}
```

**What is the expected behavior?**
![image](https://user-images.githubusercontent.com/14323780/108926927-45e57a80-768f-11eb-83bc-1337582acc7e.png)

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.8.6, Windows, Internet Explorer 11

**Comment by bmolnar2** [comment]
Hi all!

That change on the body style, removing `flex 1 1`, cause as an another problem. Considering a ToastContainer with fixed width:
```
<ToastContainer
  newestOnTop
  closeButton={false}
  closeOnClick={false}
  transition={Slide}
  style={{ width: '591px', cursor: 'default' }}
/>
```
, the body's div does not grows with the container's size, but only with the content's grows. This leaves us with the situation of having oddly narrow toast messages:
![image](https://user-images.githubusercontent.com/17888368/111796700-57055e00-88c0-11eb-96dc-8e8dea72e390.png)

instead of our desired width previously:
![image](https://user-images.githubusercontent.com/17888368/111797088-bbc0b880-88c0-11eb-8c70-4ce4b4c3f51b.png)

I gotta admit, I'm not an expert on CSS styles, but could not make the custom Toast content to stretch with it's outer `div` that is the direct child of the `Toastify__toast-body` div.

Do you have a workaround for this? Is the `Toastify__toast-body` div really stops the child div from stretching, if it's content does not make the div to grow?

**Comment by bmolnar2** [comment]
Never mind my question. I realized that I can just override the class style in a new scss file and include, that will override the body. :)

**Comment by jkamleh** [comment]
@bmolnar2 Hi Bence, I'm not sure what you mean when you refer to removal of `flex 1 1`. The proposed changes in PR #573 only **add** `width: 100%;` to toast body. Even the workaround I mentioned (e.g. your own code), by specifying `.Toastify__toast-body` only adds to the existing stylesheets (unless you override existing styles defined in the SCSS)?

**Comment by bmolnar2** [comment]
@jkamleh, sorry, I did not link the change. It wasn't #573 , but this: https://github.com/fkhadra/react-toastify/commit/468d54513148ba1bcad5124640f8b8080ce176aa
Probably I thought this bug was reported as one caused by the latter.

For my case, the solution was to override the style in SCSS. Obviously not with the change you proposed, but whatever is necessary (e.g. adding back `flex 1 1`).

The point is that you can customize certain class styles of the lib, so unless that was a change concerning every user, it doesn't make sense to revert any piece of change for my case. (Not like anyone was considering it. :D)

**Comment by fkhadra** [comment]
@bmolnar2 tbh I don't remember why I've removed `flex 1 1`, maybe a mistake from my side. I'll dig deeper

**Comment by fkhadra** [comment]
Ok, I remember why I did it... I forgot to revert this thing 🤣
