### ISSUE TITLE
HTML not rendered

### ISSUE THREAD

**Issue by mazimazur** [fkhadra/react-toastify#582]
Documentation says that there's more than a string to render. If I put HTML in it (`<button>Test</button>`) it gets not rendered. Output remains `<button>Test</button>` instead of rendering the button.

**Comment by fkhadra** [comment]
@mazimazur please share a codesandbox with the issue

**Comment by mazimazur** [comment]
It's quite a large application, but the example is simple, please see this video: https://recordit.co/IHXgbUFOyl

**Comment by fkhadra** [comment]
The issue in your case is that you are passing a string instead of jsx. 
Your translation is defined outside of react runtime, so the `<div>your content</div>` is not transformed to jsx but interpreted as a string.
[![Edit magical-wiles-3fw9u](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/magical-wiles-3fw9u?fontsize=14&hidenavigation=1&theme=dark)
