### ISSUE TITLE
Toast disappears immediately after nextjs router.push

### ISSUE THREAD

**Issue by hyposlasher** [fkhadra/react-toastify#610]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Toast disappears immediately after nextjs router.push
**If the current behavior is a bug, please provide the steps to [reproduce]([url](url)) and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

```
import { useRouter } from `'next/router';`
import { toast } from 'react-toastify';

export const Button () => {
  const router = useRouter();

  return (
    <button
      onClick={() => {
         toast("Wow so easy!");
         router.push('/home')
      }}
     />
  )
}
```
**What is the expected behavior?**
Toast does not disappears immediately after nextjs router.push

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
    "react": "16.13.1",
    "next": "10.0.3",

**Comment by hanseonghye** [comment]
I have same problem

**Comment by fs-innonova** [comment]
Hi @chrishrb sorry for late reply, the problem was actually not with react-toastify but with my own routing setup. Try to check "preserve log" in the developer tools section to see if you have any error while navigating between routes.. I had a 404 that I could not see and that error was causing the react-toastify to not appear. I hope it helps someone..
