### ISSUE TITLE
[Bug] Doesn't work with Electron App

### ISSUE THREAD

**Issue by ceoshikhar** [fkhadra/react-toastify#656]
**What is the current behavior?**
When clicked on "Notify" button, toasts are generated as shown below:

![image](https://user-images.githubusercontent.com/62669971/134209505-d9c7b1c7-2997-4f39-8e54-a219cb1d555c.png)

You can reproduce this by starting with [Electron React Boilerplate](https://github.com/electron-react-boilerplate/electron-react-boilerplate) and add `react-toastify`.

```tsx
// App.tsx

export default function App() {
  const notify = () => toast('🦄 Wow so easy!');

  return (
    <div>
      <Router>
        <Switch>
          <Route path="/" component={Hello} />
        </Switch>
      </Router>
      <button type="button" onClick={notify}>
        Notify !
      </button>
      <ToastContainer />
    </div>
  );
}
```

**What is the expected behavior?**

For toast to render in top right as shown in demo

![image](https://user-images.githubusercontent.com/62669971/134209864-e530d9ed-68e0-4fb3-a8c5-8873aa3c0f9f.png)

**Comment by fkhadra** [comment]
Hey @ceoshikhar, did you import the css file ?

**Comment by ceoshikhar** [comment]
Yes I did. I tried with both of them (minified). I tried it in `App.tsx` and in `index.tsx`. Still they render like that.

**Comment by fkhadra** [comment]
Hey @ceoshikhar, for an unknown reason the CSS classes are not picked up, probably due to how the electron boilerplate is configured. Anyway, instead of importing the CSS you can inject the style as follow
```js
import { injectStyle } from 'react-toastify/dist/inject-style';

// call it once in your app
injectStyle();
``` 
<img width="1071" alt="Screenshot 2021-09-24 at 21 27 01" src="https://user-images.githubusercontent.com/5574267/134730171-1de0535b-cadb-4f09-9852-4817bb823913.png">
