### ISSUE TITLE
Disabling the icon individually with `icon: false` not working properly on latest version

### ISSUE THREAD

**Issue by tkounenis** [fkhadra/react-toastify#658]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Icon is not hidden when passing `icon: false` upon calling any toast render methods

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**
Example of the bug being reproduced here: https://codesandbox.io/s/sad-sanderson-doc6y?file=/src/App.js

**What is the expected behavior?**
When clicking the button, the toast notification should only show text without an icon

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Tested with React v17

**Comment by fkhadra** [comment]
Thank you for reporting the issue.

**Comment by mario-iliev** [comment]
@fkhadra This bug is still reproducible if the prop is passed to the ToastContainer or the "toast" function. I see that the fix you did was only for "useToastContainer". This is in version 9.0.0. I confirm that there is no problem for version 8.2.0
I saw that the "icon" prop is not described here: https://fkhadra.github.io/react-toastify/api/toast-container
But at the same time it's working in 8.2.0
There's some confusion of what's the difference between 9.0.0 and 8.2.0
Cheers anyway and thanks for your work!

**Comment by BPreisner** [comment]
> @fkhadra This bug is still reproducible if the prop is passed to the ToastContainer or the "toast" function. I see that the fix you did was only for "useToastContainer". This is in version 9.0.0. I confirm that there is no problem for version 8.2.0 I saw that the "icon" prop is not described here: [fkhadra.github.io/react-toastify/api/toast-container](https://fkhadra.github.io/react-toastify/api/toast-container) But at the same time it's working in 8.2.0 There's some confusion of what's the difference between 9.0.0 and 8.2.0 Cheers anyway and thanks for your work!

+1 from me, I am also experiencing this issue in 9.0.0 😞

**Comment by fkhadra** [comment]
I've released a new patch version to fix this
