### ISSUE TITLE
onClose props has 1s delay

### ISSUE THREAD

**Issue by DjovDev** [fkhadra/react-toastify#685]
```
        toast(<Msg/>, { 
          onClose : () => console.log('closing'), //this has aprox 1s delay
          onOpen : () => console.log('opening') //this is instant
        })
```

**Comment by DjovDev** [comment]
Possible duplicate of https://github.com/fkhadra/react-toastify/issues/487 ?

**Comment by fkhadra** [comment]
Hey @DjovDev, `onClose` is called after the exit transition is completed. Even though the notification is not visible on the screen when removed, the exit animation is not completed, hence the delay.

**Comment by claytonrothschild** [comment]
I also ran into this problem, where the delay causes the user to lose his "instruction" but he can still take his "action" within one second. This causes UX problems.

I dont want to convolute the library (which is great), but I do propose exploring these additional callbacks:
- `onDismiss` or `onAutoClose` - when the toast is dismissed automatically rather than thru user interaction
- `onCloseStart` and `onCloseEnd` - self-explanatory

**Comment by jihea-park** [comment]
@fkhadra 
Same opinion as @claytonrothschild .
what about add `onCloseStart` handler?
