### ISSUE TITLE
toast.loading() doesn't close after toast.update() with autoClose parameter

### ISSUE THREAD

**Issue by Altereyo** [fkhadra/react-toastify#712]
Hi

When i trying to call an .update() to a toast.loading, it succesfully updates, but doesn't close with autoClose parameter. 

My piece of code:
```
const toastLoading = toast.loading("Registering...");
registerTeam()
    .then((res) => {
        toast.update(toastLoading, { render: "Team registered!", type: "success", isLoading: false, autoClose: 2000 });
    }
```

I did all directly from [this official guide](https://fkhadra.github.io/react-toastify/promise), but it doesn't work

**Comment by sgarcia-dev** [comment]
Same problem as above^

In case it helps @Altereyo , I ended up just using `toast.info(..., { autoClose: false})` instead of`toast.loading` and managed to get it to work. Ex:
```
const toastLoading = toast.info("Registering...", { autoClose: false });
registerTeam()
    .then((res) => {
        toast.update(toastLoading, { render: "Team registered!", type: "success", isLoading: false, autoClose: 2000 });
    }
```

The only minor difference is the loading icon isn't show with `toast.info`, but I disabled icons regardless.

**Comment by fkhadra** [comment]
Is it the same as https://github.com/fkhadra/react-toastify/issues/725 ?

**Comment by Rafatcb** [comment]
@fkhadra I noticed another bug that may have the same source — that's why I'm not opening a new issue.

When I try to updated a `loading` toast and change its `className`, it's not updated if the toast is updated too fast (e.g. in 100ms). I created a repro on [Code Sandbox](https://codesandbox.io/s/toastify-update-classname-bug-wl55f8?file=/src/App.js). This bug was introduced on v8.2.0.

| v8.1.1 | v8.2.0 |
| ------ | ------- |
| ![className applied when updating the toast for both 100ms and 1000ms of delay](https://user-images.githubusercontent.com/26308880/160111343-000c7692-fa49-4abc-9a7e-fe3696b0679f.png) | ![className not applied when updating the toast for both 100ms](https://user-images.githubusercontent.com/26308880/160111795-2c23a72e-2385-4aad-bef1-f4f2a86e1feb.png)  |

It was probably introduced by this commit: https://github.com/fkhadra/react-toastify/commit/25808ac2ce7ef70e5e003fe6d9af45455c8d786e

**Comment by fkhadra** [comment]
@Rafatcb thank you for the reproduction. I'll have a look

**Comment by fkhadra** [comment]
@Rafatcb I managed to fix the bug locally. I'll do my best to plan a release this weekend. Huge thank you for the reproduction it's helped a lot

**Comment by Rafatcb** [comment]
I'm glad it helped! Looking forward to seeing how you managed to fix this issue. Thanks for the lib and the replies 😀

**Comment by erictompkins** [comment]
@fkhadra I'm also having issues with toast not closing on click when using `toast.update()`. This update may fix my issue. Do you know when you will release a new update?

**Comment by PhanhotboY** [comment]
I found the same problem and found the issue was that I mistakenly put 2 `<ToastContainer/>`
