### ISSUE TITLE
react-toastify changing class-names

### ISSUE THREAD

**Issue by Enebz** [fkhadra/react-toastify#732]
**Problem**
I would like to be able to change the default class-names in the file where you find the css variables.

**Why**
I am trying to use [https://github.com/GoogleChromeLabs/container-query-polyfill/](url) with my react project, however the `container-query-polyfill` doesn't allow `@container` tags nested inside `@media` tags. The issue lies on `container-query-polyfill`'s side because the polyfill matches the `.Toastify__toast-container` as a `@container`-tag. This is a bug on their side, but while I wait for a fix on their end, I want to be able to use the polyfill together with toastify by changing the class-names.

Thank you for understanding!

**Comment by fkhadra** [comment]
Hey Sorry for the late reply @Enebz. It's not possible to change the class names using CSS variables. What you could try is to use `injectStyle` helper instead of importing the CSS file. You can call `injectStyle` after your polyfill see https://fkhadra.github.io/react-toastify/how-to-style/#inject-style-on-demand
