### ISSUE TITLE
React toast is showing multiple time. 

### ISSUE THREAD

**Issue by Rafin31** [fkhadra/react-toastify#744]
Hello, I am using react toasty in my project. I was doing a simple authentication with firebase. There I was trying to show a toast after user login. But the same toast is keep showing again and again .

**Comment by pachkovska** [comment]
Please see this issue - https://github.com/fkhadra/react-toastify/issues/741. At the bottom there are two reproduction sandboxes. This issue seems to be unique to using react-toastify in react 18. According to one of the comments, disabling strict mode in react solved an issue. It did not however work for me.
