### ISSUE TITLE
Empty data object in NotificationCenter's notifications

### ISSUE THREAD

**Issue by ingro** [fkhadra/react-toastify#757]
Hi there! I'm trying the new NotificationCenter addon, but I found an issue accessing the data object from the notification.

For example when I insert a new toast like this (as reported in the [documentation](https://fkhadra.github.io/react-toastify/addons/use-notification-center#notifications)) :

```js
toast('Lorem Ipsum', {
    type: 'success',
    data: {
        foo: 'bar'
    }
})
```

I expect to find the data object when I cycle the notifications from the hook `useNotificationCenter` but it's always an empy object (`{}`).

I've updated the example sandbox to show the problem: https://codesandbox.io/s/mui-notification-center-forked-sg5e5h

I hope that I didn't miss anything, let me know if you need more infos to replicate the issue.

**Comment by C3ntraX** [comment]
I have the same problem.

If I want to add data to 
`toast.error("Message", { data: "test" })`

Than I cant access the data in 
`toast.onChange`.

But i need this to be working, because the onClose event does trigger twice, once it is mounted and again on unmounted.
Which is a bug, this shouldn´t happen.

Additional, if I want to add two toast with the same toastId, I get the error "Encountered two children with the same key."

**Comment by fkhadra** [comment]
Hey @ingro sorry for that. Fix incoming

**Comment by fkhadra** [comment]
fix released

**Comment by ingro** [comment]
Thanks man much appreciated! 👍
