### ISSUE TITLE
When setting custom animation, toasts do not dissapear from html layout.

### ISSUE THREAD

**Issue by olegKusov** [fkhadra/react-toastify#873]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

When setting custom animation, toasts do not dissapear from html layout.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your CodeSandbox (https://codesandbox.io/s/new) example below:**

```
export default function appendToastContainerToBody(
    props?: ToastContainerProps,
) {
    const rootElement = document.createElement('div');
    rootElement.className = 'Mx-ToastContainer';

    document.body.appendChild(rootElement);

    ReactDOM.render(<ToastContainer {...props} />, rootElement);
}


const customTransition = cssTransition({
    enter: 'animate__customIn',
    exit: 'animate__customOut',
});

appendToastContainerToBody({
    autoClose: 10000,
    closeButton: false,
    transition: customTransition,
});

```

**What is the expected behavior?**

Close button must work. Reducer with type '1' is works well and returns filtered list if toasts in source code of toastify.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Chrome, Firefox

react: 16.14
react-toastify 7.0.3

**Comment by fkhadra** [comment]
Hey @olegKusov can you share a repository or a codesanbox with a reproduction please. Thanks

**Comment by max9599** [comment]
Hey @fkhadra we just started to use react-toastify and encountered same issue.

Using latest version 9.1.1

Container and transition:
`
const Transition = cssTransition({
    enter: 'animated slideInUp',
    exit: 'animated fadeOutDown',
})

<ToastContainer position="bottom-center" theme="dark" hideProgressBar autoClose={2000} transition={Transition} />
`

If i spam fast:
`
toast(errorMessage, { type: 'error' })
`
some toasts are removed, some left in the DOM, which causes overlap with app content, so that I cant click controls etc.

If I remove transition property - everything works perfectly.

Thanks!

**Comment by fkhadra** [comment]
@max9599 the latest version switched to `useSyncExternalStore`, it should fix that issue.
